config/routes.rb
Rails.application.routes.draw do
  resources :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    end
  end

  def destroy
    Recipe.destroy(params[:id])
    redirect_to recipes_path
  end



  private
  def recipe_params
    params.require(:recipe).permit(:name, :ingredients)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeCrud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/edit.html.erb
<%= form_for @recipe do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :ingredients %>
<%= f.text_field :ingredients %>
<br>
<%= f.submit "Edit Recipe" %>
<% end %>

app/views/recipes/index.html.erb
<% @recipes.each do |recipe| %>
<%= recipe.name %> - <%= recipe.ingredients %>
<br>
<%= link_to "View Recipe", recipe_path(recipe) %>
<%= link_to "Delete Recipe", recipe_path(recipe), method: "delete" %>
<br>
<hr>
<%= link_to "New Recipe", new_recipe_path %>

<% end %>

app/views/recipes/new.html.erb
<%= form_for @recipe do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :ingredients %>
<%= f.text_field :ingredients %>
<br>
<%= f.submit "Create Recipe" %>
<% end %>

app/views/recipes/show.html.erb
<%= @recipe.name %>
<br>
<%= @recipe.ingredients %>
<br>
<%= link_to "Edit Recipe", edit_recipe_path(@recipe) %>
<%= link_to "Delete Recipe", recipe_path(@recipe), method: "delete" %>